table 'MSP growth'
	lineageTag: e22f21b2-12cd-4be0-b751-c3171377997f

	measure 'MSP growth %' =
			
			DIVIDE(SUM('MSP growth'[numerator]), SUM('MSP growth'[denominator]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eefe1e5f-abbd-4c20-84c7-0bb33850b81e

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "MathematicalDivision",
				  "version": 0
				}

		changedProperty = FormatString

	measure 'MSP Growth % NSW' = ```
			
			CALCULATE(
			    DIVIDE(SUM('MSP growth'[numerator]), SUM('MSP growth'[denominator])),
			    KEEPFILTERS ( allvillage[State] = "NSW" )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 10bae525-04dc-4a5d-bcfa-e805e475131a

	measure 'MSP Growth % QLD' = ```
			
			CALCULATE(
			    DIVIDE(SUM('MSP growth'[numerator]), SUM('MSP growth'[denominator])),
			    KEEPFILTERS ( allvillage[State] = "QLD" )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fbb62acb-f3f7-446b-8442-794db633e197

	measure 'MSP Growth % SA' = ```
			
			CALCULATE(
			    DIVIDE(SUM('MSP growth'[numerator]), SUM('MSP growth'[denominator])),
			    KEEPFILTERS ( allvillage[State] = "SA" )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6cb8afb2-0055-44ea-834a-c516335707d5

	measure 'MSP Growth % VIC' = ```
			
			CALCULATE(
			    DIVIDE(SUM('MSP growth'[numerator]), SUM('MSP growth'[denominator])),
			    KEEPFILTERS ( allvillage[State] = "VIC" )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0ff1b5c9-1341-4f66-a5a6-3b5de2001a66

	measure 'MSP Growth % ACT' = ```
			
			CALCULATE(
			    DIVIDE(SUM('MSP growth'[numerator]), SUM('MSP growth'[denominator])),
			    KEEPFILTERS ( allvillage[State] = "ACT" )
			)
			
			```
		lineageTag: 76ac4cfa-3466-4e2d-adb0-252d25cefc86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column kpi_name
		dataType: string
		lineageTag: 1d537596-eca6-4b2d-9d8a-f1ed2f68e1c5
		summarizeBy: none
		sourceColumn: kpi_name

		annotation SummarizationSetBy = Automatic

	column reporting_month
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 0d07552d-cbab-4d6b-b18d-ecc14791d386
		summarizeBy: none
		sourceColumn: reporting_month

		variation Variation
			isDefault
			relationship: a245e930-0e9d-4761-9f75-747f2e176870
			defaultHierarchy: LocalDateTable_be6d13ba-7860-4f0d-ae8c-8fcf6cdf40c6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column village_code
		dataType: string
		lineageTag: 6177069c-74ed-4a95-96d1-2ae96c9eb369
		summarizeBy: none
		sourceColumn: village_code

		annotation SummarizationSetBy = Automatic

	column summary_type
		dataType: string
		lineageTag: 539c675f-49a6-4d6d-b7b1-2b74cb6a21d2
		summarizeBy: none
		sourceColumn: summary_type

		annotation SummarizationSetBy = Automatic

	column kpi_group
		dataType: string
		lineageTag: 5d8a3381-5211-4686-9071-f1d0ce29df4d
		summarizeBy: none
		sourceColumn: kpi_group

		annotation SummarizationSetBy = Automatic

	column data_type
		dataType: string
		lineageTag: 36775e9f-425f-496a-bfa5-0c26ec11bf31
		summarizeBy: none
		sourceColumn: data_type

		annotation SummarizationSetBy = Automatic

	column decimals
		dataType: int64
		formatString: 0
		lineageTag: 254d5750-f49a-48dc-965a-ce51d845e61a
		summarizeBy: sum
		sourceColumn: decimals

		annotation SummarizationSetBy = Automatic

	column numerator
		dataType: double
		lineageTag: 9cb4e227-49f0-4907-bb44-3a1c0f608d90
		summarizeBy: sum
		sourceColumn: numerator

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column denominator
		dataType: double
		lineageTag: 589bf4f1-e713-43c2-a384-deaf10124cf9
		summarizeBy: sum
		sourceColumn: denominator

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'MSP growth' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(Databricks.Catalogs("adb-3752096125893962.2.azuredatabricks.net", "sql/protocolv1/o/3752096125893962/0306-040335-bqgo537k", [Catalog="hive_metastore", Database=null, EnableAutomaticProxyDiscovery=null]){[Name="hive_metastore",Kind="Database"]}[Data], "select #(lf)#(lf)'MSP growth (% p.a.)' AS kpi_name#(lf),date_trunc('month',val.date) as reporting_month#(lf)--,val.assetid#(lf),val.location as village_code#(lf),'Average' AS summary_type#(lf),'None' kpi_group#(lf),'Percent' as data_type#(lf),2 as decimals#(lf),SUM(val.value) AS numerator#(lf),SUM(cast(base.value as decimal (25,5))) AS denominator#(lf)#(lf)from (#(lf)#(lf)select cal.date ,unit.AssetId, ass.location#(lf),cast(unit.MarketValue as decimal (25,5)) as value#(lf)from hive_metastore.gold.calendar cal#(lf)left join hive_metastore.standardised_dynamics365_db.rlm_unitdetails unit on cal.date between unit.audit_start_date and unit.audit_end_date#(lf)left join hive_metastore.standardised_dynamics365_db.assettable ass on unit.AssetId = ass.AssetId and ass.audit_is_current = 1#(lf)Inner join (select  distinct date_add(add_months(date_trunc('month',date),1),-1) as month_end from hive_metastore.gold.calendar) month  on cal.date = month.month_end#(lf)where  cal.date <= current_date()#(lf)and ass.AssetGroup = 'UNIT'#(lf)and unit.AssetType <> 3 #(lf)#(lf)#(lf)union all#(lf)#(lf)select #(lf)hist.period,#(lf)hist.unit_number,#(lf)ass.location,#(lf)cast(hist.value  as decimal (25,5)) as value#(lf) from hive_metastore.standardised_manual_msp_list_db.price_list_jan_22_to_sep_23 hist#(lf)left join hive_metastore.standardised_dynamics365_db.assettable ass on hist.unit_number = ass.AssetId and ass.audit_is_current = 1#(lf)left join hive_metastore.standardised_dynamics365_db.rlm_unitdetails unit on ass.assetid = unit.assetid and unit.audit_is_current = 1#(lf)#(lf)where hist.period < '2023-08-30'#(lf)and ass.AssetGroup = 'UNIT'#(lf)and unit.AssetType <> 3  #(lf)#(lf)) val#(lf)left join hive_metastore.standardised_manual_msp_list_db.price_list_jan_22_to_sep_23 base on val.AssetId = base.unit_number and base.period = '2022-06-30'#(lf)#(lf)--where assetid = 'KNSC.060'#(lf)--where val.location = '5KNRV'#(lf)where location is not null#(lf)and date_trunc('month',val.date)  >= '2022-06-01T00:00:00.000+0000' and date_trunc('month',val.date) < date_trunc('month', current_date())#(lf)#(lf)group by 1,2,3,4,5,6,7", null, [EnableFolding=true])
				in
				    Source

	annotation PBI_ResultType = Table

